version: '3.7'

services:
  postgres:
    image: postgres:14.1
    ports:
      - '8090:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: x_clone_app
      POSTGRES_PASSWORD: "DbTh_NE6QCi-6_3UgBVKBHQLtz6DRTBv"
    volumes:
      - x_clone_app_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6
    ports:
      - '8091:6379'
    command: redis-server --requirepass "zSUZnB7pWUXICkyURtXMtB6BOQPhcbp-"
    environment:
      - REDIS_REPLICATION_MODE=master
volumes:
  x_clone_app_data:
