name: x_clone_app_flutter
description: A new Flutter project with Serverpod.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  auto_route: ^7.8.4
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.4
  flutter_secure_storage: ^9.0.0
  flutter_verification_code: ^1.1.7
  freezed: ^2.4.6
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  hooks_riverpod: ^2.4.9
  serverpod_auth_email_flutter: 1.2.2
  serverpod_auth_shared_flutter: 1.2.2
  serverpod_flutter: 1.2.2
  x_clone_app_client:
    path: ../x_clone_app_client

dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.8
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
